# Generated by Django 5.2.7 on 2025-10-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
