# Generated by Django 5.2.7 on 2025-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='org_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
