# Generated by Django 5.2.7 on 2025-10-25 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('government', 'Government'), ('publisher', 'Publisher')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('vc_issuer_did', models.CharField(blank=True, max_length=255, null=True)),
                ('vc_status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('pending', 'Pending'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('vc_proof', models.JSONField(blank=True, default=dict)),
                ('vc_type', models.CharField(blank=True, default='GovernmentPublicationCredential', max_length=100, null=True)),
                ('vc_issuance_date', models.DateTimeField(blank=True, null=True)),
                ('vc_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
