# Generated by Django 5.2.7 on 2025-10-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='proof',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
