# Generated by Django 5.2.7 on 2025-11-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_didkey'),
        ('vcs', '0002_post_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSchemaVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('schema_url', models.URLField()),
                ('schema_context', models.JSONField()),
                ('credential_id', models.CharField(max_length=200, unique=True)),
                ('ai_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('vc_metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
