# Generated by Django 5.2.7 on 2025-11-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_didkey'),
        ('vcs', '0003_generatedschemavc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSchemaVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('schema', models.JSONField()),
                ('schema_s3_url', models.URLField()),
                ('vc_document', models.JSONField()),
                ('vc_s3_url', models.URLField()),
                ('ai_score', models.FloatField(default=0.0)),
                ('issuance_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_credentials', to='users.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneratedSchemaVC',
        ),
    ]
